/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hy351_project;

import static Utilities.Amax.cancel_Appointment;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Amax
 */
public class Cancel_Appointment extends javax.swing.JFrame {

    /**
     * Creates new form Cancel_Appointment
     */
    public Cancel_Appointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        vaccinationCenterLabel2 = new javax.swing.JLabel();
        vaccinationCenterLabel3 = new javax.swing.JLabel();
        doseDropdown = new javax.swing.JComboBox<>();
        jButtonCancel_Appointment = new javax.swing.JButton();
        amkaTextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Back_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vaccinationCenterLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel2.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel2.setText("AMKA :");
        jPanel2.add(vaccinationCenterLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 50, 22));

        vaccinationCenterLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel3.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel3.setText("Dose :");
        jPanel2.add(vaccinationCenterLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 40, 22));

        doseDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Dose", "1", "2" }));
        doseDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doseDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(doseDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 201, -1));

        jButtonCancel_Appointment.setBackground(new java.awt.Color(255, 102, 51));
        jButtonCancel_Appointment.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonCancel_Appointment.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancel_Appointment.setText("Cancel Appointment");
        jButtonCancel_Appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancel_AppointmentActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel_Appointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, 30));
        jPanel2.add(amkaTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 200, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cancel an Appointment");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 340, 40));

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(Back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doseDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doseDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doseDropdownActionPerformed

    private void jButtonCancel_AppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancel_AppointmentActionPerformed

        if (doseDropdown.getSelectedIndex() == 0 || amkaTextfield.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Some fields are empty.\nCouldn't Cancel Appointment.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        String amka = amkaTextfield.getText();
        String dose = doseDropdown.getSelectedItem().toString();

        try {
            String Appointment_ID = cancel_Appointment(amka, dose);
            if (Appointment_ID != "") {
                JOptionPane.showMessageDialog(null, "Appointment with ID " + Appointment_ID + " is canceled");
            } else {
                JOptionPane.showMessageDialog(null, "Cannot cancel Appointment.\n You are already vaccinated.\n or make sure your AMKA or dose No. is correct.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "You don't have such an appointment", "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Cancel_Appointment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCancel_AppointmentActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed

        this.setVisible(false);
        UserHomepage EP = new UserHomepage();
        EP.setVisible(true);
        EP.pack();
        EP.setTitle("User Homepage");
        EP.setLocationRelativeTo(null);
        EP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_Back_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancel_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancel_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancel_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancel_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancel_Appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JTextField amkaTextfield;
    private javax.swing.JComboBox<String> doseDropdown;
    private javax.swing.JButton jButtonCancel_Appointment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel vaccinationCenterLabel2;
    private javax.swing.JLabel vaccinationCenterLabel3;
    // End of variables declaration//GEN-END:variables
}
