/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hy351_project;

import Utilities.RB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Delete_Account extends javax.swing.JFrame {

    /**
     * Creates new form Delete_Account
     */
    public Delete_Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AMKA_textfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Password_textfield = new javax.swing.JPasswordField();
        Confirm_Button = new javax.swing.JButton();
        Cancel_Button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 169, 168));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Delete Account");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 240, 30));

        AMKA_textfield.setBackground(new java.awt.Color(255, 255, 255));
        AMKA_textfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AMKA_textfield.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(AMKA_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 210, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("AMKA :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 110, 40));

        Password_textfield.setBackground(new java.awt.Color(255, 255, 255));
        Password_textfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Password_textfield.setForeground(new java.awt.Color(0, 0, 0));
        Password_textfield.setText("jPasswordField1");
        jPanel1.add(Password_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 210, 40));

        Confirm_Button.setBackground(new java.awt.Color(153, 153, 153));
        Confirm_Button.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Confirm_Button.setForeground(new java.awt.Color(255, 0, 0));
        Confirm_Button.setText("Confirm");
        Confirm_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Confirm_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 130, 40));

        Cancel_Button.setBackground(new java.awt.Color(153, 153, 153));
        Cancel_Button.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Cancel_Button.setForeground(new java.awt.Color(0, 0, 0));
        Cancel_Button.setText("Cancel");
        Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 130, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 300, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_ButtonActionPerformed

        this.setVisible(false);
        UserHomepage TH = new UserHomepage();
        TH.setVisible(true);
        TH.pack();
        TH.setTitle("HappyVax Homepage");
        TH.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_Cancel_ButtonActionPerformed

    
    
    /*Function to delete Account of Citizen behind the confirm button*/
    private void Confirm_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_ButtonActionPerformed
        
        String amka = AMKA_textfield.getText();
        String password = Password_textfield.getText();
       
        System.out.println("amka is: "+ amka + " and password is: "+ password);
        
        int yes_no = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete your account?","Confirmation Message",JOptionPane.YES_NO_OPTION,2);
        
        if(yes_no == JOptionPane.YES_OPTION){
            
            if(amka == null || password == null){
                JOptionPane.showMessageDialog(null, "One Or More Empty Field!");
            }
            else{
               
               if(RB.check_delete(amka, password) == true){
                   JOptionPane.showMessageDialog(null, "The user deleted successfully!");
               }
               else if(RB.check_delete(amka, password) == false){
                   JOptionPane.showMessageDialog(null, "The user can not be deleted because he already has an active dose of vaccine!");
               }
            }
        }
        else{
            
        }
        
        /*
        String amka = AMKA_textfield.getText();
        String password = Password_textfield.getText();
        int Dose = 0;
        System.out.println("amka is: "+ amka + " and password is: "+ password);
        
        
        int yes_no = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete your account?","Confirmation Message",JOptionPane.YES_NO_OPTION,2);
        
        if(yes_no == JOptionPane.YES_OPTION){
            
        
        if(amka == null || password == null){
            JOptionPane.showMessageDialog(null, "One Or More Empty Field!");
        }
        else{
            try {
                Connection con = MyConnection.getConnection();
                Statement stmt = con.createStatement();
                ResultSet rs;
            
                rs = stmt.executeQuery("SELECT * FROM citizen WHERE Citizen_AMKA = '" + amka + "' AND password = '" + password + "' AND Num_Of_Dose = '" + Dose + "'");
            
                if(rs.next()){
                    String deleteQuery = "DELETE FROM citizen WHERE Citizen_AMKA = '" + amka +"'";
                    stmt.executeUpdate(deleteQuery);
                    stmt.close();
                    con.close();
                    JOptionPane.showMessageDialog(null, "The user deleted successfully!");
                    this.setVisible(false);
                    Homepage TH = new Homepage();
                    TH.setVisible(true);
                    TH.pack();
                    TH.setTitle("HappyVax Start Page");
                    TH.setLocationRelativeTo(null);
                }
                else{
                    JOptionPane.showMessageDialog(null, "The user can not be deleted because he already has an active dose of vaccine!");
                }
            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "The user can not be deleted!\nTry again Later!");
                System.err.println("Got an exception!");
            }    
        }
        } else{
           
        }*/
        
    }//GEN-LAST:event_Confirm_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AMKA_textfield;
    private javax.swing.JButton Cancel_Button;
    private javax.swing.JButton Confirm_Button;
    private javax.swing.JPasswordField Password_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
