/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hy351_project;

import static Utilities.Amax.Confirm_Identity;
import static Utilities.Amax.Update_Details;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Amax
 */
public class Edit_Profile extends javax.swing.JFrame {

    /**
     * Creates new form Edit_Profile
     */
    public Edit_Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelProfilePage = new javax.swing.JLabel();
        jLabelAMKA = new javax.swing.JLabel();
        jTextFieldAMKA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonUpdate = new javax.swing.JButton();
        jLabelAMKA1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabelAMKA2 = new javax.swing.JLabel();
        jTextFieldAMKA1 = new javax.swing.JTextField();
        jLabelPassword1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelBirthdate = new javax.swing.JLabel();
        jTextFieldSex = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelTelephone = new javax.swing.JLabel();
        jTextFieldBirthdate1 = new javax.swing.JTextField();
        jTextFieldDoses = new javax.swing.JTextField();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jButtonbackToHomepagefromRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelTelephone1 = new javax.swing.JLabel();
        jTextFieldTelephone1 = new javax.swing.JTextField();
        jButtonConfirmIdentity = new javax.swing.JButton();
        jTextFieldUsername1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProfilePage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelProfilePage.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabelProfilePage.setForeground(new java.awt.Color(0, 0, 102));
        jLabelProfilePage.setText("Edit Profile Page");
        jPanel1.add(jLabelProfilePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 13, -1, -1));

        jLabelAMKA.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAMKA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelAMKA.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAMKA.setText("AMKA:");
        jPanel1.add(jLabelAMKA, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 169, -1, -1));

        jTextFieldAMKA.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAMKA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldAMKA.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldAMKA, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 165, 265, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Your Personal Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabelPassword.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPassword.setText("Password:");
        jPanel1.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 228, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setPreferredSize(new java.awt.Dimension(120, 32));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 224, 267, -1));

        jButtonUpdate.setBackground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(0, 0, 0));
        jButtonUpdate.setText("Update Details");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, 200, -1));

        jLabelAMKA1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAMKA1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelAMKA1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAMKA1.setText("Citizen ID:");
        jPanel1.add(jLabelAMKA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jTextFieldID.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldID.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 200, 30));

        jLabelUsername.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUsername.setText("Username:");
        jPanel1.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, -1, -1));

        jTextFieldPassword.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldPassword.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 200, 200, -1));

        jLabelAMKA2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAMKA2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelAMKA2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAMKA2.setText("AMKA:");
        jPanel1.add(jLabelAMKA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        jTextFieldAMKA1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAMKA1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldAMKA1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldAMKA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 200, 30));

        jLabelPassword1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPassword1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPassword1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPassword1.setText("Password:");
        jPanel1.add(jLabelPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, 100, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("First Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Last Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        jTextFieldFirstName.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFirstName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldFirstName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 200, -1));

        jTextFieldLastName.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldLastName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldLastName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 200, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sex:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        jLabelBirthdate.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBirthdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelBirthdate.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBirthdate.setText("Date of Birth:");
        jPanel1.add(jLabelBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        jTextFieldSex.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSex.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jTextFieldSex.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSexActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 200, -1));

        jLabelEmail.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEmail.setText("Email:");
        jPanel1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, -1, -1));

        jLabelTelephone.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTelephone.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTelephone.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTelephone.setText("No. of doses:");
        jPanel1.add(jLabelTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, 120, -1));

        jTextFieldBirthdate1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldBirthdate1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jTextFieldBirthdate1.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldBirthdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBirthdate1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBirthdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 200, -1));

        jTextFieldDoses.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDoses.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldDoses.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldDoses, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 350, 200, -1));

        jTextFieldEmail1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldEmail1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, 200, -1));

        jButtonbackToHomepagefromRegister.setBackground(new java.awt.Color(255, 255, 255));
        jButtonbackToHomepagefromRegister.setForeground(new java.awt.Color(0, 0, 0));
        jButtonbackToHomepagefromRegister.setText("Back");
        jButtonbackToHomepagefromRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackToHomepagefromRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonbackToHomepagefromRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Please Confirm your Identity first");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabelTelephone1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTelephone1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTelephone1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTelephone1.setText("Telephone:");
        jPanel1.add(jLabelTelephone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, 100, -1));

        jTextFieldTelephone1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTelephone1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldTelephone1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldTelephone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, 200, -1));

        jButtonConfirmIdentity.setBackground(new java.awt.Color(255, 255, 255));
        jButtonConfirmIdentity.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonConfirmIdentity.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConfirmIdentity.setText("Confirm Identity");
        jButtonConfirmIdentity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmIdentityActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConfirmIdentity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 270, -1));

        jTextFieldUsername1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUsername1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldUsername1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 150, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        /* GET Profile Details */
        String AMKA = jTextFieldAMKA1.getText();
        String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        String email = jTextFieldEmail1.getText();
        Boolean flag = email.matches(EMAIL_REGEX);

        String password = jTextFieldPassword.getText();
        String Telephone = jTextFieldTelephone1.getText();

        if (password != "" && Telephone != "" && email != "") {

            if (flag) {

                try {
                    if (Update_Details(AMKA, password, email, Telephone)) {
                        JOptionPane.showMessageDialog(null, "Profile Details Updated Successfuly.", "Success", JOptionPane.PLAIN_MESSAGE);
                        this.setVisible(false);
                        UserHomepage homepage = new UserHomepage();
                        homepage.setVisible(true);
                        homepage.setTitle("User Home Page");
                        homepage.pack();
                        homepage.setLocationRelativeTo(null);
                        homepage.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Edit_Profile.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Something went wrong.\nCouldn't Update User's Details.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {

                /* Empty Input Fields */
                JOptionPane.showMessageDialog(null, "Email format is wrong.", "Error", JOptionPane.ERROR_MESSAGE);

            }

        } else {

            /* Empty Input Fields */
            JOptionPane.showMessageDialog(null, "Input Fields are empty.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTextFieldSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSexActionPerformed

    private void jTextFieldBirthdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBirthdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBirthdate1ActionPerformed

    private void jButtonbackToHomepagefromRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackToHomepagefromRegisterActionPerformed

        this.setVisible(false);
        UserHomepage homepage = new UserHomepage();
        homepage.setVisible(true);
        homepage.setTitle("User Home Page");
        homepage.pack();
        homepage.setLocationRelativeTo(null);
        homepage.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonbackToHomepagefromRegisterActionPerformed

    /* CONFIRM IDENTITY */
    private void jButtonConfirmIdentityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmIdentityActionPerformed

        try {
            /* Get Fields */
            String AMKA = jTextFieldAMKA.getText();
            String Password = jPasswordField1.getText();

            List<String> citizen_fields = new ArrayList<String>();

            citizen_fields = Confirm_Identity(AMKA, Password);

            if (!citizen_fields.isEmpty()) {

                JOptionPane.showMessageDialog(null, "Identification Succeeded.", "Success", JOptionPane.PLAIN_MESSAGE);

                /* Display Profile Details */
                jTextFieldID.setText(citizen_fields.get(0));
                jTextFieldID.setEditable(false);
                jTextFieldID.setForeground(Color.DARK_GRAY);
                jTextFieldAMKA1.setText(citizen_fields.get(1));
                jTextFieldAMKA1.setEditable(false);
                jTextFieldAMKA1.setForeground(Color.DARK_GRAY);
                jTextFieldFirstName.setText(citizen_fields.get(9));
                jTextFieldFirstName.setEditable(false);
                jTextFieldFirstName.setForeground(Color.DARK_GRAY);
                jTextFieldLastName.setText(citizen_fields.get(10));
                jTextFieldLastName.setEditable(false);
                jTextFieldLastName.setForeground(Color.DARK_GRAY);
                jTextFieldSex.setText(citizen_fields.get(2));
                jTextFieldSex.setEditable(false);
                jTextFieldSex.setForeground(Color.DARK_GRAY);
                jTextFieldBirthdate1.setText(citizen_fields.get(3));
                jTextFieldBirthdate1.setEditable(false);
                jTextFieldBirthdate1.setForeground(Color.DARK_GRAY);
                jTextFieldUsername1.setText(citizen_fields.get(8));
                jTextFieldUsername1.setEditable(false);
                jTextFieldUsername1.setForeground(Color.DARK_GRAY);
                jTextFieldPassword.setText(citizen_fields.get(7));
                jTextFieldEmail1.setText(citizen_fields.get(5));
                jTextFieldTelephone1.setText(citizen_fields.get(4));
                jTextFieldDoses.setText(citizen_fields.get(6));
                jTextFieldDoses.setEditable(false);
                jTextFieldDoses.setForeground(Color.DARK_GRAY);

            } else {

                /* Failure */
                JOptionPane.showMessageDialog(null, "Identification Failed.\nPlease try again.", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Edit_Profile.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonConfirmIdentityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmIdentity;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonbackToHomepagefromRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAMKA;
    private javax.swing.JLabel jLabelAMKA1;
    private javax.swing.JLabel jLabelAMKA2;
    private javax.swing.JLabel jLabelBirthdate;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPassword1;
    private javax.swing.JLabel jLabelProfilePage;
    private javax.swing.JLabel jLabelTelephone;
    private javax.swing.JLabel jLabelTelephone1;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldAMKA;
    private javax.swing.JTextField jTextFieldAMKA1;
    private javax.swing.JTextField jTextFieldBirthdate1;
    private javax.swing.JTextField jTextFieldDoses;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldSex;
    private javax.swing.JTextField jTextFieldTelephone1;
    private javax.swing.JTextField jTextFieldUsername1;
    // End of variables declaration//GEN-END:variables
}
