/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hy351_project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Edit_Appointment extends javax.swing.JFrame {

    /**
     * Creates new form Edit_Appointment
     */
    public Edit_Appointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        vaccinationCenterDropdown = new javax.swing.JComboBox<>();
        vaccinationCenterLabel = new javax.swing.JLabel();
        vaccineNameDropdown = new javax.swing.JComboBox<>();
        vaccinationCenterLabel1 = new javax.swing.JLabel();
        vaccinationCenterLabel2 = new javax.swing.JLabel();
        monthDropdown = new javax.swing.JComboBox<>();
        vaccinationCenterLabel3 = new javax.swing.JLabel();
        doseDropdown = new javax.swing.JComboBox<>();
        yearDropdown = new javax.swing.JComboBox<>();
        timeDropdown = new javax.swing.JComboBox<>();
        vaccinationCenterLabel4 = new javax.swing.JLabel();
        dayDropdown = new javax.swing.JComboBox<>();
        book_button = new javax.swing.JButton();
        amkaTextfield = new javax.swing.JTextField();
        vaccinationCenterLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Back_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vaccinationCenterDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Vaccination Center", "PAGNI Hospital", "Venizeleio Hospital" }));
        vaccinationCenterDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinationCenterDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(vaccinationCenterDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 201, -1));

        vaccinationCenterLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel.setText("Vaccination Center :");
        jPanel2.add(vaccinationCenterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 143, 22));

        vaccineNameDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Vaccine Name", "Moderna", "Oxford/AstraZeneca", "Pfizer/BioNTech" }));
        vaccineNameDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineNameDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(vaccineNameDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 201, -1));

        vaccinationCenterLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel1.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel1.setText("Vaccine Name :");
        jPanel2.add(vaccinationCenterLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 143, 22));

        vaccinationCenterLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel2.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel2.setText("AMKA :");
        jPanel2.add(vaccinationCenterLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 143, 22));

        monthDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(monthDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 100, -1));

        vaccinationCenterLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel3.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel3.setText("Dose :");
        jPanel2.add(vaccinationCenterLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 143, 22));

        doseDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Dose", "1", "2" }));
        doseDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doseDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(doseDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 201, -1));

        yearDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        yearDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(yearDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 60, -1));

        timeDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Time", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00" }));
        timeDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(timeDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 70, -1));

        vaccinationCenterLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel4.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel4.setText("Date :");
        jPanel2.add(vaccinationCenterLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 143, 22));

        dayDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        dayDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(dayDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 60, -1));

        book_button.setBackground(new java.awt.Color(51, 255, 255));
        book_button.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        book_button.setForeground(new java.awt.Color(0, 0, 0));
        book_button.setText("Edit");
        book_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(book_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 120, 30));
        jPanel2.add(amkaTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 150, -1));

        vaccinationCenterLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel5.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel5.setText("Time :");
        jPanel2.add(vaccinationCenterLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 143, 22));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Edit an Appointment");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 300, 40));

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(Back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vaccinationCenterDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinationCenterDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccinationCenterDropdownActionPerformed

    private void vaccineNameDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineNameDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineNameDropdownActionPerformed

    private void monthDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthDropdownActionPerformed

    private void doseDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doseDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doseDropdownActionPerformed

    private void yearDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearDropdownActionPerformed

    private void timeDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeDropdownActionPerformed

    private void dayDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayDropdownActionPerformed

    private void book_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_buttonActionPerformed

        if (vaccinationCenterDropdown.getSelectedIndex() == 0
            || vaccineNameDropdown.getSelectedIndex() == 0
            || doseDropdown.getSelectedIndex() == 0
            || dayDropdown.getSelectedIndex() == 0
            || monthDropdown.getSelectedIndex() == 0
            || yearDropdown.getSelectedIndex() == 0
            || timeDropdown.getSelectedIndex() == 0
            || amkaTextfield.getText().equals("")) {
            
        }
    
        String vaccinationCenter = vaccinationCenterDropdown.getSelectedItem().toString();
        String vaccineName = vaccineNameDropdown.getSelectedItem().toString();
        String dose = doseDropdown.getSelectedItem().toString();
        int day = dayDropdown.getSelectedIndex();
        int month = monthDropdown.getSelectedIndex();
        String year = yearDropdown.getSelectedItem().toString();
        String amka = amkaTextfield.getText();
        String time = timeDropdown.getSelectedItem().toString();
        String date = Integer.toString(day) + "/" + Integer.toString(month) + "/" + year;
        System.out.println(vaccinationCenter);
    try{ 
        Connection con = MyConnection.getConnection();
        Statement stmt = con.createStatement();
        ResultSet rs;
        
        rs = stmt.executeQuery("SELECT * FROM appointment WHERE Citizen_AMKA = '" + amka + "' AND Dose = '" + dose + "'");
            
        if(rs.next()){
            
             String update = "UPDATE appointment SET Vaccination_Center_ID='" + vaccinationCenter + "',Vaccine_Name='" + vaccineName +
                     "',Dose='" + dose + "',Date='" + date + "',Time='" + time + "' WHERE Citizen_AMKA = '" + amka + "'";
                
                stmt.executeUpdate(update);
                stmt.close();
                con.close();
                JOptionPane.showMessageDialog(null, "Τhe user's appointment with AMKA " + amka + "\nwas successfully Edited!");
        }
        else{
             JOptionPane.showMessageDialog(null, "The user does not have any active appointment, or wrong details!");
        }
    }
    catch(SQLException e){
        System.out.println(e);
    }
            
        
        
    }//GEN-LAST:event_book_buttonActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        
        this.setVisible(false);
        UserHomepage EP = new UserHomepage();
        EP.setVisible(true);
        EP.pack();
        EP.setTitle("User Homepage");
        EP.setLocationRelativeTo(null);
        EP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_Back_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JTextField amkaTextfield;
    private javax.swing.JButton book_button;
    private javax.swing.JComboBox<String> dayDropdown;
    private javax.swing.JComboBox<String> doseDropdown;
    private javax.swing.JButton jButtonbackToHomepagefromRegister;
    private javax.swing.JButton jButtonbackToHomepagefromRegister1;
    private javax.swing.JButton jButtonbackToHomepagefromRegister2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> monthDropdown;
    private javax.swing.JComboBox<String> timeDropdown;
    private javax.swing.JComboBox<String> vaccinationCenterDropdown;
    private javax.swing.JLabel vaccinationCenterLabel;
    private javax.swing.JLabel vaccinationCenterLabel1;
    private javax.swing.JLabel vaccinationCenterLabel2;
    private javax.swing.JLabel vaccinationCenterLabel3;
    private javax.swing.JLabel vaccinationCenterLabel4;
    private javax.swing.JLabel vaccinationCenterLabel5;
    private javax.swing.JComboBox<String> vaccineNameDropdown;
    private javax.swing.JComboBox<String> yearDropdown;
    // End of variables declaration//GEN-END:variables
}
