/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hy351_project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kesenia
 */
public class UserHomepage extends javax.swing.JFrame {

    /**
     * Creates new form UserHomepage
     */
    public UserHomepage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuItem3 = new javax.swing.JMenuItem();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        vaccinationCenterDropdown = new javax.swing.JComboBox<>();
        vaccinationCenterLabel = new javax.swing.JLabel();
        vaccineNameDropdown = new javax.swing.JComboBox<>();
        vaccinationCenterLabel1 = new javax.swing.JLabel();
        vaccinationCenterLabel2 = new javax.swing.JLabel();
        monthDropdown = new javax.swing.JComboBox<>();
        vaccinationCenterLabel3 = new javax.swing.JLabel();
        doseDropdown = new javax.swing.JComboBox<>();
        yearDropdown = new javax.swing.JComboBox<>();
        timeDropdown = new javax.swing.JComboBox<>();
        vaccinationCenterLabel4 = new javax.swing.JLabel();
        dayDropdown = new javax.swing.JComboBox<>();
        bookAppButton = new javax.swing.JButton();
        amkaTextfield = new javax.swing.JTextField();
        vaccinationCenterLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuEdit_Profile = new javax.swing.JMenu();
        DeleteAccount_Item = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Covid_Certificate = new javax.swing.JMenu();
        Apply_for_certificate = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Edit_Appointment_Item = new javax.swing.JMenuItem();
        Cancel_Appointment_Item = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("jMenu5");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jLabel1.setText("jLabel1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vaccinationCenterDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Vaccination Center", "PAGNI Hospital", "Venizeleio Hospital" }));
        vaccinationCenterDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinationCenterDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(vaccinationCenterDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 201, -1));

        vaccinationCenterLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel.setText("Vaccination Center :");
        jPanel2.add(vaccinationCenterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 143, 22));

        vaccineNameDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Vaccine Name", "Moderna", "Oxford/AstraZeneca", "Pfizer/BioNTech" }));
        vaccineNameDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineNameDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(vaccineNameDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 201, -1));

        vaccinationCenterLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel1.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel1.setText("Vaccine Name :");
        jPanel2.add(vaccinationCenterLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 143, 22));

        vaccinationCenterLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel2.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel2.setText("AMKA :");
        jPanel2.add(vaccinationCenterLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 143, 22));

        monthDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(monthDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 100, -1));

        vaccinationCenterLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel3.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel3.setText("Dose :");
        jPanel2.add(vaccinationCenterLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 143, 22));

        doseDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Dose", "1", "2" }));
        doseDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doseDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(doseDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 201, -1));

        yearDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        yearDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(yearDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 60, -1));

        timeDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Time", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00" }));
        timeDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(timeDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 70, -1));

        vaccinationCenterLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel4.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel4.setText("Date :");
        jPanel2.add(vaccinationCenterLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 143, 22));

        dayDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        dayDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(dayDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 60, -1));

        bookAppButton.setText("Book");
        bookAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAppButtonActionPerformed(evt);
            }
        });
        jPanel2.add(bookAppButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));
        jPanel2.add(amkaTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 150, -1));

        vaccinationCenterLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccinationCenterLabel5.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationCenterLabel5.setText("Time :");
        jPanel2.add(vaccinationCenterLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 143, 22));

        jTabbedPane2.addTab("Book an Appointment", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/got-my-covid-19-vaccine-feeling-great-meme.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel2)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("My Appointments", jPanel1);

        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.setPreferredSize(new java.awt.Dimension(224, 35));

        jMenuEdit_Profile.setBorder(null);
        jMenuEdit_Profile.setText("Account");
        jMenuEdit_Profile.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        DeleteAccount_Item.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeleteAccount_Item.setText("Delete Account");
        DeleteAccount_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAccount_ItemActionPerformed(evt);
            }
        });
        jMenuEdit_Profile.add(DeleteAccount_Item);

        jRadioButtonMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Edit Profile");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenuEdit_Profile.add(jRadioButtonMenuItem1);

        jMenuBar2.add(jMenuEdit_Profile);

        jMenu3.setText("   ");
        jMenu3.setEnabled(false);
        jMenuBar2.add(jMenu3);

        Covid_Certificate.setBorder(null);
        Covid_Certificate.setText(" Covid-19 Certificate");
        Covid_Certificate.setAlignmentX(4.0F);
        Covid_Certificate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Covid_Certificate.setPreferredSize(new java.awt.Dimension(230, 25));
        Covid_Certificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Covid_CertificateActionPerformed(evt);
            }
        });

        Apply_for_certificate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Apply_for_certificate.setText("Apply");
        Apply_for_certificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apply_for_certificateActionPerformed(evt);
            }
        });
        Covid_Certificate.add(Apply_for_certificate);

        jMenuBar2.add(Covid_Certificate);

        jMenu2.setText("Appointments");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        Edit_Appointment_Item.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Edit_Appointment_Item.setText("Edit Appointment");
        Edit_Appointment_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_Appointment_ItemActionPerformed(evt);
            }
        });
        jMenu2.add(Edit_Appointment_Item);

        Cancel_Appointment_Item.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cancel_Appointment_Item.setText("Cancel Appointment");
        Cancel_Appointment_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_Appointment_ItemActionPerformed(evt);
            }
        });
        jMenu2.add(Cancel_Appointment_Item);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteAccount_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAccount_ItemActionPerformed

        Delete_Account DA = new Delete_Account();
        DA.setVisible(true);
        DA.pack();
        DA.setTitle("Delete Account");
        DA.setLocationRelativeTo(null);

    }//GEN-LAST:event_DeleteAccount_ItemActionPerformed

    private void Covid_CertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Covid_CertificateActionPerformed

    }//GEN-LAST:event_Covid_CertificateActionPerformed

    private void Apply_for_certificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apply_for_certificateActionPerformed
        Covid_Certificate_Apply DA = new Covid_Certificate_Apply();
        DA.setVisible(true);
        DA.pack();
        DA.setTitle("Covid-19 Certificate Application");
        DA.setLocationRelativeTo(null);
    }//GEN-LAST:event_Apply_for_certificateActionPerformed

    private void vaccinationCenterDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinationCenterDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccinationCenterDropdownActionPerformed

    private void vaccineNameDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineNameDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineNameDropdownActionPerformed

    private void monthDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthDropdownActionPerformed

    private void doseDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doseDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doseDropdownActionPerformed

    private void yearDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearDropdownActionPerformed

    private void timeDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeDropdownActionPerformed

    private void dayDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayDropdownActionPerformed

    private void bookAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAppButtonActionPerformed

        if (vaccinationCenterDropdown.getSelectedIndex() == 0
                || vaccineNameDropdown.getSelectedIndex() == 0
                || doseDropdown.getSelectedIndex() == 0
                || dayDropdown.getSelectedIndex() == 0
                || monthDropdown.getSelectedIndex() == 0
                || yearDropdown.getSelectedIndex() == 0
                || timeDropdown.getSelectedIndex() == 0
                || amkaTextfield.getText().equals("")) {

        }

        String vaccinationCenter = vaccinationCenterDropdown.getSelectedItem().toString();
        String vaccineName = vaccineNameDropdown.getSelectedItem().toString();
        String dose = doseDropdown.getSelectedItem().toString();
        int day = dayDropdown.getSelectedIndex();
        int month = monthDropdown.getSelectedIndex();
        String year = yearDropdown.getSelectedItem().toString();
        String amka = amkaTextfield.getText();
        String time = timeDropdown.getSelectedItem().toString();

        System.out.println(vaccinationCenter);
        Connection con = MyConnection.getConnection();
        PreparedStatement ps;

        try {

            ps = con.prepareStatement("INSERT INTO appointment(Vaccination_Center_ID,Vaccine_Name,Citizen_AMKA,Dose,Date,Time) VALUES (?,?,?,?,?,?)");

            ps.setString(1, vaccinationCenter);
            ps.setString(2, vaccineName);
            ps.setString(3, amka);
            ps.setString(4, dose);
            ps.setString(5, Integer.toString(day) + "/" + Integer.toString(month) + "/" + year);
            ps.setString(6, time);

            if (ps.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Appointment Booked Succesfuly!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserHomepage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bookAppButtonActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed

        this.setVisible(false);
        Edit_Profile EP = new Edit_Profile();
        EP.setVisible(true);
        EP.pack();
        EP.setTitle("User Profile");
        EP.setLocationRelativeTo(null);
        EP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void Edit_Appointment_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_Appointment_ItemActionPerformed

        this.setVisible(false);
        Edit_Appointment EP = new Edit_Appointment();
        EP.setVisible(true);
        EP.pack();
        EP.setTitle("Edit an Appointment");
        EP.setLocationRelativeTo(null);
        EP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_Edit_Appointment_ItemActionPerformed

    private void Cancel_Appointment_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_Appointment_ItemActionPerformed

        this.setVisible(false);
        Cancel_Appointment CP = new Cancel_Appointment();
        CP.setVisible(true);
        CP.pack();
        CP.setTitle("Cancel your Appointment");
        CP.setLocationRelativeTo(null);
        CP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_Cancel_Appointment_ItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Apply_for_certificate;
    private javax.swing.JMenuItem Cancel_Appointment_Item;
    private javax.swing.JMenu Covid_Certificate;
    private javax.swing.JMenuItem DeleteAccount_Item;
    private javax.swing.JMenuItem Edit_Appointment_Item;
    private javax.swing.JTextField amkaTextfield;
    private javax.swing.JButton bookAppButton;
    private javax.swing.JComboBox<String> dayDropdown;
    private javax.swing.JComboBox<String> doseDropdown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuEdit_Profile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox<String> monthDropdown;
    private javax.swing.JComboBox<String> timeDropdown;
    private javax.swing.JComboBox<String> vaccinationCenterDropdown;
    private javax.swing.JLabel vaccinationCenterLabel;
    private javax.swing.JLabel vaccinationCenterLabel1;
    private javax.swing.JLabel vaccinationCenterLabel2;
    private javax.swing.JLabel vaccinationCenterLabel3;
    private javax.swing.JLabel vaccinationCenterLabel4;
    private javax.swing.JLabel vaccinationCenterLabel5;
    private javax.swing.JComboBox<String> vaccineNameDropdown;
    private javax.swing.JComboBox<String> yearDropdown;
    // End of variables declaration//GEN-END:variables
}
